### ISSUE TITLE
虽说是娱乐性测试，但是也太离谱了点

### ISSUE THREAD

**Issue by StevensonXuan** [CNValues/cnvalues.github.io#13]
我一个正统马克思主义者到这就成了进步保守主义
很多题目没有前提，选项也是非黑即白
我试过开摆，每个题目都啊对对对过去，全选强烈同意，你猜是啥？进步保守主义  全选强烈反对，你猜是啥？社会自由主义
我人傻了.jpg

**Comment by tzf1003** [comment]
你用谎言去验证谎言，得到的一定是谎言

**Comment by Meritamen** [comment]
腊左滚
