### ISSUE TITLE
计算结果时{choice=Math.max(choice,0)}导致反对立场变成中立的问题

### ISSUE THREAD

**Issue by Tieria-von-Veda** [CNValues/cnvalues.github.io#2]
if(questions[i].effect[axis]>0){choice=Math.max(choice,0)}
else{choice=Math.min(choice,0)}
这个不允许得分结果为负分的算法，实际上使得立场加分题的反对和立场扣分题的同意都被赋值成了中立值0,实际上就是把反对立场变成了中立,从(强烈同意,同意,中立,反对,强烈反对)变成了不对称,非线性的(强烈同意,同意,中立),导致立场判断出现显著偏差

直观地说，对得分统计的影响就是，导致表达的反对立场无效,只能支持或中立(无意见),
从而导致一些整体上反对某个立场A的人做题时，大多数关于A的题目选反对意见的选择结果被整合到0分（中立）而不是扣分，少数关于A的题目选支持意见就在立场A上加分，测试结果竟然是支持该立场A。

从政治科学的角度来看，这是非常不科学的，建议重新设计算法，允许负分，使支持选项和反对选项都能平等计分。

**Comment by CNValues** [comment]
已修改
