### ISSUE TITLE
Inquiry 

### ISSUE THREAD

**Issue by strandedhorse** [CNValues/cnvalues.github.io#3]
Hi, team,
Great work! I am a journalist. I'm much interested in the project and am curious to know your survey results. I'd like to work with you and report your findings. Could you email me at [strandedhorse@protonmail.com](url) so that we could talk more about it?
Thank you in advance. I look forward to hearing from you.

**Comment by CNValues** [comment]
I'm sorry, but this project is completely front-end and open source. We don't collect any test results. It's just a test, not a survey.

**Comment by strandedhorse** [comment]
thanks for getting back to me!

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
