### ISSUE TITLE
关于可访问性的建议

### ISSUE THREAD

**Issue by sakura-yuina** [CNValues/cnvalues.github.io#6]
由于Github Pages在中国大陆的可访问性十分可怜(遭遇各种DNS污染以及TCP阻断
故 ''' MiaoTeam ''' 愿意为CN Values项目提供*免费*的托管支持,并且会***定期同步此库***
托管地址为 https://miao.team/cnvalues/ 望准许

**Comment by railgun19982** [comment]
瞅瞅我碰到了谁

**Comment by railgun19982** [comment]
恁先把noyacg的坑填了

**Comment by CNValues** [comment]
这个小破玩具不值得如此费心，如果不怕麻烦，您请便……
